### ISSUE TITLE
I need help, it broke my game

### ISSUE THREAD

**Issue by shrimpolin** [mastercomfig/team-comtress-2#157]
My game is not starting up, I did everything right and i removed the config i had on, everything is with the default settings, i have steam open and when i try to run the game it says "running" but it doesn't do anything, the game is not opening, and i have no idea what to do or what i did wrong

**Comment by treacherousfiend** [comment]
Read the installation instructions again.

You are _NOT_ supposed to install comtress over your current tf2 installation
You _CANNOT_ play on TF2 servers with it, this is a testing ground for changes that will be sent to valve to hopefully be implemented in the official build of TF2.
Even if you could get your game to somehow recognize TF2 servers, _it cannot play on them_ because this is technically a pre jungle inferno build of the game.

**Comment by Yttrium-tYcLief** [comment]
In addition to what @treacherousfiend , if you verify your TF2 game cache (and delete the included HUD from your custom folder) it *should* return your game to a modern playable state
