### ISSUE TITLE
Quality of life change for kill-icons with NeoDement's mod/fix

### ISSUE THREAD

**Issue by z0nk285** [mastercomfig/team-comtress-2#529]
### Description

The current TF2 kill-icons are trash and everyone knows it, that's why NeoDements Consistent Killicon Pack should be implemented into TC2 https://steamcommunity.com/sharedfiles/filedetails/?id=1520&searchtext=icons this pack includes better-looking icons and new icons to help clarify what you were truly killed by. some of these icons may be out of date like the crusader's crossbow with an arrow projectile and some others but this is better than what we currently have. with this pack, there are some choices for full or halved kill icons, personally, I like full icon and for either rockets or launchers I prefer the launchers. there could be a settings menu to change the icons but that seems like a bit much, really hope this gets added.
### Checklist

- [x] None of the open *or* closed issues document this idea.
- [x] This is a new idea, not a bug.
- [x] This idea does not seriously affect game balance.
- [ ] This is obviously an improvement, not something that people commonly disagree on.
- [ ] This is not an idea for new game content (e.g. new weapons, maps, sounds).

- [ ] This idea is for the code of the game, not for textures, sounds, or other resources.
- [ ] This idea has been implemented in vanilla TF2.
- [ ] There is proof that this idea is well liked (e.g. a history of use of a similar mod in a competitive league).
- [x] This idea has been implemented in a mod. <https://gamebanana.com/skins/141376> (most mods are outdated or broken)
- [ ] This feature has existed in the vanilla game but was removed.
- [ ] This idea is for internal procedures or tooling (e.g. improving the build process, supporting new systems).

### Screenshots

 http://killicons.jennybur.net/preview.jpg

**Comment by MeDerpWasTaken** [comment]
> This is obviously an improvement, not something that people commonly disagree on.
might want to uncheck that one as this is completely opinion based

**Comment by int-72h** [comment]
This is opinion based rather than a literal fix (like agrastiOs' visual fix pack), so I don't think this should be merged in. Though mastercoms has the final say.

**Comment by Malfunktion-issues** [comment]
While, yes, the current kill icons are garbage, only a few of the icons in this pack seem like objective improvements. The rest are either more detailed (which considering the killfeed's minimalist style, look off), recolored (the Brass Beast's is almost unintelligible), or just lengthened (making the killfeed take up more space).

**Comment by MikhailaTF** [comment]
Personally I'm quite a fan of this mod and I have been using it for just about as long as I can remember, add the small updates some people over at gamebanana have made and the pack is almost complete.
While I praise this mod under the slogan of "consistency is key" I can understand that it is indeed more of a subjective thing. 

I would however argue that the width fixes (because they are literally fixes), the proposed new kill icons (because they allow specified information) and the tribalman's shiv kill icon (because [the wiki](https://wiki.teamfortress.com/wiki/Kill_icon) states that the original creator submitted a fix to Valve because the icon is upside-down but Valve has yet to implement it)
I do believe there may be a place for these additions within this project.

Of note may also be that the same author has made [a similar mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2156604959) more recently that adds a few more specific kill icons for situations that previously used the generic skull and crossbones (I feel like these would fit the pack for the same reason the proposed new kill icons of the previous mod would). The mod even comes with the same width fixes as the other one! I do figure however that this is the about only part of the community fix-up pack that has not been implemented into Team Comtress 2 so perhaps there's a good reason that neither of this mods as a whole fit the scope of this project.

**Comment by DankMachine** [comment]
This exactly.
I love this mod, I absolutely prefer it over the normal ones for consistency, but not everyone does. In a world of changes, some people will always prefer what they’re used to.
This is the same argument as the custom first person animations. A lot of people think it’s an improvement, but not everyone likes them.
The ones that do things like fix the widths and add icons to the Bat Outta Hell, Medigun shield, Telefragging, Grappling Hook, Short Circuit Ball, Sentry Buster, Gas Passer, and a few reflect kills, those should be in the main game.
People aren’t gonna complain that a weapon actually has a kill icon and not a skull and bones.

**Comment by sbritorodr** [comment]
I'm sorry. That's a cool mod but I think it'f off from the purpose of this project, to be honest.

**Comment by DankMachine** [comment]
I discovered the Community Fix-Up Pack was already added, which already has the Missing Kill Icons pack

**Comment by sbritorodr** [comment]
> I discovered the Community Fix-Up Pack was already added, which has the Missing Kill Icons pack

So, close the discussion I guess??

**Comment by agrastiOs** [comment]
The whole Pack was not added.

**Comment by DankMachine** [comment]
This ain’t my discussion, this is @z0nk285’s, and they’re talking about the Consistent Icons pack, which many of us, including myself, are arguing against

**Comment by agrastiOs** [comment]
I'm aware. The point to close the discussion was because this has already been added, however. Don't see any other valid points to do so in this issue's page.

**Comment by mastercoms** [comment]
I don't think it fits
