### ISSUE TITLE
TF2 vs TC2 performance + bug list

### ISSUE THREAD

**Issue by hoffr** [mastercomfig/team-comtress-2#64]
EDIT 9/7/2020: i'm not experienced with rapidly evolving repos like this so this thread is kind of a mess, sorry bout that. from now on I'm going to only post benchmark data in this thread and all bug reports or suggestions will be separate

---

note that this info applies only to the official valve tf2 on steam. my observations aren't code-oriented and frankly tf2's source kinda scares me. i've also been away from this stuff for half a year so i might forget certain details

i'm sure you've already fixed a number of things i'm gonna mention and a lot of it is probably super obvious. i've read all release notes but haven't run any builds, also can't always mentally correlate certain changes with their practical impact. i might as well share since i had spent a lot of time observing performance related stuff over the years, testing, all that. anyway, hope you can get at least one useful thing out of it

---

performance observations for official valve tf2:

- on less than high end systems especially, there may be significantly higher and more flux 'input latency' on dx9 vs dx8, regardless of what shaders are disabled via cvars

    for instance, disabling or reducing as many shaders and processing as possible on dx9 will greatly reduce input delay vs stock dx9, but nowhere near to dx8's extent. it also won't disable shaders on certain things, such as the little player model in the corner if that's enabled. latency in tf2 is not directly tied to frame rates but is affected by it. 120fps in dx8 for me is far less delayed than 120fps in dx9. older source games like hl2 don't have this issue at all, even when it's assumed that tf2 with my cfg is running far less shaders than hl2 is

- in dx8, certain world static detail props are not drawn at all such as bushes, grass, wall mounted hoses, horseshoes, nails

- number of players on the server, especially rendered at once is probably the number 1 thing that tanks performance, secondarily if those players are creating objects, particles, projectile models, tracers, bullet impacts, sound, etc. simply adding real players to a map even with little to no player activity tanks fps (have seen drops from avg 500fps to 150 as players load into a server) while looking at real, mostly hatless players on a remote server who are doing almost nothing at all (such as waiting in spawn on payload attack during setup, not firing weapons, vocalizing or even moving or looking much)

- map geometry and/or number of static props drawn at once greatly affect render performance and input latency on a low-mid end system, observed primarily on cp_mossrock

- i've observed it over the years where with more active and more complex shaders, game freezes/stutter is more frequent and lasts longer per freeze

- game hangs are known to be caused at least in part by match hud updating (this one's really bad for me), players joining a team (even if weapon skins are disabled, nohats mod is enabled & match hud is disabled), and viewmodel weapon skins loading in. freezes do happen without visleaf involvement, for example standing still, no mouselook, not near/facing any sliding doors

- aside from what i already listed, in vague order of performance impact on my low-mid end rig: antialiasing, wearable cosmetics, reducefillrate/worldlights, 3dsky on/off, glow outlines/spawn hax, player texture-rendered shadows, mat_phong, ropes, rootlod, bumpmap/specular/other shaders. everything else individually seem to make unnoticeable differences to framerate alone (still probably important to toggle them in batch)

---

bugs for official valve tf2:

- loading a timedemo on one map and then another timedemo on another map in the same game session will reduce avg framerate by 10-20% on the second demo

    note: running timedemo on any unique demo gives a lower avg framerate on the first run, and higher frames on subsequent runs. this was accounted for when i observed the framerate reduction on the second unique demo, both were run multiple times in a row

- mat_filterlightmaps 0 does not stick if set before joining a server. it is automatically set back on map load, but does not reflect the change through the cvar and it remains 0 until manually set to 1, and then it can be set back to 0. it will continue to revert in the same way though on each class change

- mod_lock_mdls_on_load crashes when set to 1. can crash either on server disconnect or after quitting out of game

**Comment by micwoj92** [comment]
that dx9 vs dx8 section is kinda useless as mastercoms removed dx8 and ported most impactful changes to be enabled via cvars

**Comment by hoffersrc** [comment]
it's moreso a comment on the rendering systems themselves, since some newer games with lots of shaders don't have the issue. not sure if those kinds of things are subject to change, but according to release notes rendering has been cleaned up a bit, though i'm not sure in what ways or to what extent

**Comment by mastercoms** [comment]
I'd recommend running Team Comtress so that you can evaluate it separately from TF2 so that you can give more useful feedback.

**Comment by hoffersrc** [comment]
i will see about doing that soon

**Comment by hoffersrc** [comment]
here comes a lotta text. lemme know if this should be uh, sent in some different manner, or if i just talk way too much

---

### BENCHMARKS:

**method:**

set "-default -autoconfig +quit", then set dx95, then set res/gfx (4x aniso, no aa, all else very high/on, 1920x1080), then loaded new session (every set of values is from a brand new session unless otherwise stated)

ran timedemo multiple times and stopped. demos between tc2 and tf2 are nearly identical

settings for tc2 and tf2: all highest, vsync off, multicore on, aniso 4x, aa off, hdr on, color correct on, motion blur on, 1920x1080 fullscreen, frames uncapped. for real tf2: match hud disabled, 66 tick, rate 100000

re-ran each timedemo until 3 consecutive values indicated the end of a pattern (well, i got a lil lazy on tf2 mossrock)


**results:**

tc2 (fps):
mossrock lots of geometry no bots or movement: 91, 91, 104, 101, 102
upward attack setup with many tf_bots: 146, 172, 170, 178, 184, 175, 173, 169
upward attack setup with many tf_bots, loaded just after mossrock timedemo: 171, 175, 180, 183, 174, 174, 176
hightower spawn, no bot present: 405 (avg of 4)
hightower spawn, 1 bot (cvar "bot", medic) alive unmoving rendered: 402 (avg of 4)

tf2 (fps):
mossrock lots of geometry no bots or movement: 89, 89, 92, 111, 110
upward attack setup with many tf_bots: 149, 154, 193, 193, 192
upward attack setup with many tf_bots, loaded just after mossrock timedemo: 191, 189, 190, 188
hightower spawn, no bot present: 557 (avg of 4)
hightower spawn, 1 bot (cvar "bot", medic) alive unmoving rendered: 500 (avg of 4)


**notes:**

i think maybe fps doesn't matter much. so far, tc2 'felt' like it performed much better than tf2, but results were similar between both, and tf2 even had higher frames in a scenario where it felt a lot worse to play


---

### SUBJECTIVE PERFORMANCE OBSERVATIONS:

in tc2 there is minor input latency on stock/very high gfx hightower no bots or players, similar to tf2. haven't tried low settings yet due to crashes described below

with listen bots though, the experience is much less stuttery and with much less input lag than real tf2. real tf2 with listen bots is almost unplayable on stock high settings. tc2 with listen bots felt similar to tc2 with no bots


---

### BUGS/ODDITIES/ETC:

**0.0.12 / 0.0.13:**

- mat_filterlightmaps 0 does not stick if set before joining a server. it is automatically set back on map load, but does not reflect the change through the cvar and it remains 0 until manually set to 1, and then it can be set back to 0. it will continue to revert in the same way though on each class change

- this was debunked and is not true in latest tf2 and tc2 0.0.12/0.0.13:

    loading a timedemo on one map and then another timedemo on another map in the same game session will reduce avg framerate by 10-20% on the second demo

**0.0.12 (0.0.13 untested):**

- "-default -autoconfig +quit" causes game to use dx10, but game used dx95 on fresh download. also, -dxlevel is telling me it can't coexist with -default (and trying gives me dx10), so i needed to run them separately
	
- may be a helpful tip for users: radeon tesselation was on 'amd optimized' by default and needed to be forced off or else all console/source menu text looked 'smooth' and fps was down by more than half


---

### CRASHES/FREEZE-UPS (for reference i almost never crash in real tf2):


**0.0.12** (these seem to be sort of random, can't methodically replicate any):

- crashed in dx10. ran mossrock timedemo twice, then on map load for another upward timedemo crashed. process memory was just under 1GB. all other crashes are in dx95

- crashed while mod_lock_mdls_on_load was enabled, just after team join. can't replicate. hasn't crashed on disconnect or quit like it does consistently in real tf2

- freeze on quit 3 times so far, have to taskman. one of those times were background freezes (could use desktop, process was using 5B cycles/sec)

- freeze while alt-tabbing back in while in a server, wouldn't load fullscreen app, showed small black rectangle in corner of desktop


**0.0.13:**

all of the following text is of one type of crash determined to be caused by shader detail set to low. it's the only crash or freeze-up i encountered in 0.0.13 vs 0.0.12, and i spent way more time in 0.0.13. feel free to skim for the **error msgs**

crashed to desktop with no errormsg. happened immediately after changing menu video settings and resolution, after having run a single demo multiple times. loaded back in and res was changed but video settings were same as before except shadows and reflections were on medium instead of either what they were before or what i set them to before the crash

settings before being changed: all highest, vsync off, multicore on, aniso 4x, aa off, hdr on, color correct on, motion blur on, 1920x1080 fullscreen

quit game after setting video settings again and loading back in, but crashed to desktop upon loading a map. this time hl2.exe needed manual termination

tried exact thing again and crashed but this time with error: **failed to lock vertex buffer in CMeshDX8::LockVertexBuffer: nVertexCount=1647, nFirstVertex=0**

tried again, same exact msg

graphics settings in menu were all low, vsync off, multicore on, aniso bi, aa off, hdr off, color correct off, motion blur off, 1280x720 fullscreen

turned gfx settings mostly back to what they were and loaded map just fine: all highest, vsync off, multicore on, aniso bi, aa off, hdr on, color correct on, motion blur on, 1280x720 fullscreen

put all back to low except kept hdr on, motion blur on, multicore on, color correct on and loaded map, but had 'leak' visuals and spammed console error: **CMaterial::DrawElements: No bound shader**

turned shader detail to high, no leak on map join. turned shader detail on low while on map, leak

decided to try all high settings again except keep shaders on low, restarted game, game crashes on map join with the lock vertex buffer msg. loaded back in, turned shaders to high, all good 


---

### MY TODO:

real, extended gameplay with remote bots (stutter/microfreeze and input lag check)
tf2: yea it's bretty bad
tc2: pending

is there less input latency when dx8 settings are used?
tf2: yes
tc2: pending

does match hud frequently microfreeze game?
tf2: yes
tc2: pending

---

### MY PC:

CPU: amd fx-6300 3c/6t 4.4Ghz locked to max clock
GPU: amd radeon rx 570 locked to max clock
HD: windows & steam on sata ssd 1, tf2/tc2 on sata ssd 2
RAM: 2x4GB 1333Mhz DDR3 (page file disabled, laugh all u want)
OS: windows (gasp) 7 (yes we still exist it's a sad reality we all live in)

background programs: only essential, nothing to impact performance
hardware/OS stability: CPU, RAM, GPU/MEM, HD's, OS all tested fine a couple months ago

**Comment by mastercoms** [comment]
Thanks for the feedback. Just a note: dxlevel 100 is preferred.

**Comment by hoffersrc** [comment]
oh whoops, got it, must've remembered the fresh state's dxlevel wrong

also, i figured this batch script could be useful for myself and possibly anyone else wanting to save disk space and time copying tf2 files, especially for versioning (unless there's an obvious way i'm totally missing). downside here is that you can't copy soft symlinks with windows explorer, only move them (gets stuck, needs termination)

note that the data i got was done with a full copy of the folder as instructed, but there don't seem to be any problems using this method

copytf2files_symlinklargefiles.bat:
```
@echo off

:: BatchGotAdmin
::-------------------------------------
REM  --> Check for permissions
>nul 2>&1 "%SYSTEMROOT%\system32\cacls.exe" "%SYSTEMROOT%\system32\config\system"

REM --> If error flag set, we do not have admin.
if '%errorlevel%' NEQ '0' (
    echo Requesting administrative privileges...
    goto UACPrompt
) else ( goto gotAdmin )

:UACPrompt
    echo Set UAC = CreateObject^("Shell.Application"^) > "%temp%\getadmin.vbs"
    set params = %*:"="
    echo UAC.ShellExecute "cmd.exe", "/c %~s0 %params%", "", "runas", 1 >> "%temp%\getadmin.vbs"

    "%temp%\getadmin.vbs"
    del "%temp%\getadmin.vbs"
    exit /B

:gotAdmin
    pushd "%CD%"
    CD /D "%~dp0"
::--------------------------------------

setlocal enableextensions
set PROMPT=$g

set src=E:\SteamLibrary\steamapps\common\Team Fortress 2
set dst=E:\Team Comtress 2\tf2_stripped
set xfn=exclude.txt


if "%src%" == "%dst%" (
    echo %0: ERROR: source-dir [%src%] and destination-dir [%dst%] are identical, nothing to do
    goto :END
)

xcopy "%src%" "%dst%" /t /e /c /i
xcopy "%src%" "%dst%" /s /c /i /exclude:%xfn%

for /r "%src%" %%f in (*.vpk) do call :PROC "%%~f"
for /r "%src%" %%f in (*.bik) do call :PROC "%%~f"
for /r "%src%" %%f in (*.bsp) do call :PROC "%%~f"

goto :END

:PROC
set sfn="%~1"
call set dfn=%%sfn:%src%=%dst%%%
mklink %dfn% %sfn%
goto :EOF

:END
pause
```

exclude.txt:
```
.vpk\
.bsp\
.bik\
.dem\
.lnk\
sound.cache\
\tf\cache\
\tf\custom\
\tf\custom_defaulthq\
\tf\screenshots\
\tf\download\
\tf\downloadlists\
\tf\replay\
\tf\workshop\
\tf\streams\
\tf\materials\temp\
config.cfg\
```

yeah i know i'm wordy but for real, i'm super impressed by the work being done on tc2. you are so fast, it's really something.

**Comment by treacherousfiend** [comment]
I'm fairly certain dxlevel 100 isn't default, its just preferred since its dxlevel 90 (or 95 for that matter) with less restrictions and maybe better performance due to using newer stuff?
