### ISSUE TITLE
Add telefrag  kill icon

### ISSUE THREAD

**Issue by micwoj92** [mastercomfig/team-comtress-2#74]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I kill someone with telefrag and it doesn't show anything significant in kill feed.

**Describe the solution you'd like**
Add separate icon for telefragging.

**Describe alternatives you've considered**
none

**Additional context**
tag https://github.com/ValveSoftware/Source-1-Games/issues/1811

**Comment by treacherousfiend** [comment]
There's already a mod on tf2 workshop that fixes this and other missing kill icons:
https://steamcommunity.com/sharedfiles/filedetails/?id=2156604959
no real need to implement it into comtress, probably better to have it be separate anyway.
works in casual too, since pure doesn't blacklist it.

**Comment by micwoj92** [comment]
What is Team Comtress 2? 
"Team Fortress 2, but with a lot of fixes, quality of life improvements and performance optimizations!"

This is without any doubt QoL improvement, this issue also exists on the Valve's bugtracker and it WAS NOT closed there, so I see no reason to not implement it into TC2.

**Comment by treacherousfiend** [comment]
Fair enough, I was more pointing out the fact that this mod already exists, and has no real reason to be implemented into comtress (agree to disagree).
Also the issue you linked has never been publicly acknowledged by anyone by valve, and has existed since 2014, its likely no one at valve ever knew the issue existed.

**Comment by wgetJane** [comment]
i'm pretty certain that valve developers themselves do not look at the issue tracker

also resolving this issue would require bundling community-made assets with comtress, and i think comtress is more focused on fixes rather than adding new content to the game

**Comment by treacherousfiend** [comment]
valve devs actually do (occasionally) check the issue tracker, but this has gone unnoticed, and the issue tracker for that is more for _bugs_ not QoL hud textures

**Comment by FIying-Scotsman** [comment]
> What is Team Comtress 2?
> "Team Fortress 2, but with a lot of fixes, quality of life improvements and performance optimizations!"
> 
> This is without any doubt QoL improvement, this issue also exists on the Valve's bugtracker and it WAS NOT closed there, so I see no reason to not implement it into TC2.

While it's a valid QoL improvement - as someone else has already mentioned, it would require community assets to be included in the project which can get murky (i.e if the original asset author isn't available to ask if it can be included) unless it's remade.

From the commits I've gone through - the main focus seems to be fixing the source code first and foremost and I'm guessing assets and other related fixes are pretty low down the list.

**Comment by Yttrium-tYcLief** [comment]
>From the commits I've gone through - the main focus right now seems to be fixing the source code first and foremost (including making QoL improvements there) and I'm guessing assets and other related fixes are pretty low down the list.

Pretty much this. I'll tag it as wontfix for now, but it's in a very niche area where it's outside of the current scope, but this project might expand to cover it in the future, so I won't close the issue.

**Comment by Shrinks99** [comment]
While I see that this has been tagged "wontfix" for now and that texture contributions are specified as being outside the scope of this project in the enhancement request template, I'd really like to see many of the community texture fixes incorporated into the base game and this project seems to be in a unique position to make that happen.  Lots of great texture fixes and their authors are [catalogued in this repo](https://github.com/ModdingTF2/The-closest-thing-to-an-updated-version-of-TF2-TIP), some of them are small enhancements, others fix straight up bugs.  I have a feeling that if original authors were contacted the vast majority of them would be very happy to have these fixes pushed to the base game.

**Comment by wgetJane** [comment]
@Shrinks99 a lot of the changes in that repo you've linked aren't "fixes", they seem to be redesigns:

<img src="https://raw.githubusercontent.com/ModdingTF2/The-closest-thing-to-an-updated-version-of-TF2-TIP/master/docs/comparison_scr.png"/>
<div><img src="https://wiki.teamfortress.com/w/images/5/54/Gibbed_Heavy_2.png" width="40%" align="center"/><img src="https://raw.githubusercontent.com/ModdingTF2/The-closest-thing-to-an-updated-version-of-TF2-TIP/master/docs/heavy_gibs.png" width="50%" align="center"/></div>

i doubt that these changes fit within the scope of the project

(pretend i sent this before coms closed the issue, she's just too fast)

**Comment by Shrinks99** [comment]
@wgetJane While I do agree that the larger changes are out of scope I still think that others in that repo such as the [cut-throat concierge fire texture fix](https://gamebanana.com/skins/126426) and the [shotgun shell texture mismatch fix](https://gamebanana.com/skins/127587) are just bugs that should probably be fixed at some point but not something that the TF2 team has gotten around to because they don't _really_ contribute to a player's experience negatively.  I agree that the larger changes should not be included as they are a little more drastic and something other people would have opinions about

![519dbc50c842b](https://user-images.githubusercontent.com/5672810/93599035-87a92100-f98b-11ea-81fd-d2e56509f1e3.jpg)
<p align="center">This is an actual bug, no?</p>

That said, I do see that this has been closed and I won't push this issue any further, if this is not within scope of this project then that's how it is!  Thanks for the work you have all done up to now. :)

**Comment by Yttrium-tYcLief** [comment]
I've rearranged the labels with our new system to more accurately describe the current stance on this.

The *reason* this is currently out of scope is because TC2 is completely detached from assets; we work on game code *only*. **If** this project ever expands to cover assets, we will most definitely revisit this issue and work on it.

**Comment by micwoj92** [comment]
> I've rearranged the labels with our new system to more accurately describe the current stance on this.
> 
> The _reason_ this is currently out of scope is because TC2 is completely detached from assets; we work on game code _only_. **If** this project ever expands to cover assets, we will most definitely revisit this issue and work on it.


Does this comment make this request valid and it should be reopened?
https://github.com/mastercomfig/team-comtress-2/pull/383#issuecomment-701695233
